//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineStickersManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblPhotoes = new HashSet<tblPhoto>();
        }
    
        public string ID { get; set; }
        public string LineID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> AccountLast5Digits { get; set; }
        public bool IsPaymentReceived { get; set; }
        public Nullable<System.DateTime> PaymentReceivedDateTime { get; set; }
        public int OrderStatus { get; set; }
        public int StickerStatus { get; set; }
        public string StickerLink { get; set; }
        public System.DateTime OrderDateTime { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhoto> tblPhotoes { get; set; }
    }
}
